image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 

stages:
  - validate
  - plan
  - apply
  - ansible_configure
  - destroy

before_script: 
  - apk update
  - apk add --no-cache gnupg python3 py3-crcmod py3-pip
  - pip install google-auth google-auth-httplib2 google-auth-oauthlib
  - apk add --no-cache ansible curl
  - ansible-galaxy collection install kubernetes.core

  - mkdir -p ./creds
  - echo $serviceaccount | base64 -d > ./creds/service_account.json

  - curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-443.0.0-linux-x86_64.tar.gz
  - tar -xzf google-cloud-cli-443.0.0-linux-x86_64.tar.gz -C /usr/local/
  - ln -s /usr/local/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud # folder link

  - gcloud components install kubectl
  - gcloud components update
  - gcloud config set core/disable_usage_reporting true
  - gcloud config set component_manager/disable_update_check true
  - gcloud --version
  - gcloud auth activate-service-account --key-file=./creds/service_account.json

  - echo 'export PATH=$PATH:/usr/local/google-cloud-sdk/bin' >> /etc/profile
  - source /etc/profile
  
  - cd terraform/
  - /usr/local/google-cloud-sdk/bin/gsutil cp gs://tf-state-bucket-mvb/default.tfstate .
  - chmod +x /usr/local/google-cloud-sdk/bin/gsutil
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile" # Reads the config file and compares to current state
  dependencies:
    - validate
  artifacts:
    paths:
      - terraform/planfile
      - terraform/default.tfstate
  except:
    - branches@projects_mvbs/sre-gitlabci-proj-2

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
  needs:
    - job: plan
      artifacts: true
  except:
    - branches@projects_mvbs/sre-gitlabci-proj-2

ansible_configure:
  stage: ansible_configure
  script:
    - cd ../ansible/
    - ansible-playbook -i inventory.ini playbook.yaml
    - gcloud container clusters get-credentials primary --zone=us-central1-a --project=pioneering-rex-394919

  needs:
    - job: apply
      artifacts: true
  except:
    - branches@projects_mvbs/sre-gitlabci-proj-2

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve
  dependencies:
    - plan
  when: manual
  except:
    - branches@projects_mvbs/sre-gitlabci-proj-2