image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 

stages:
  - validate
  - plan
  - apply
  - ansible_configure
  - destroy

before_script: 
  - sh ./install_pkg.sh 
  - cd terraform/
  - echo $tfvars | base64 -d > ./terraform.tfvars
  - /usr/local/google-cloud-sdk/bin/gsutil cp gs://tf-state-bucket-mvb/default.tfstate .
  - chmod +x /usr/local/google-cloud-sdk/bin/gsutil
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

plan:
  stage: plan
  script:
    - terraform plan -var-file="terraform.tfvars" -out "planfile" 
  dependencies:
    - validate
  artifacts:
    paths:
      - terraform/planfile
      - terraform/default.tfstate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

apply:
  stage: apply
  script:
    - terraform apply "planfile"
  dependencies:
    - plan
  when: manual
  needs:
    - job: plan
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

ansible_configure:
  stage: ansible_configure
  script:
    - cd ../ansible/
    - ansible-playbook -i inventory.ini playbook.yaml
    - gcloud container clusters get-credentials primary --zone=us-central1-a --project=pioneering-rex-394919

    # Set release names
    - FLUENT_BIT_RELEASE=my-fluent-bit
    - REDIS_RELEASE=my-redis
    - NGINX_RELEASE=my-nginx
    - POSTGRES_RELEASE=my-postgresql
    - PROMETHEUS_RELEASE=my-prometheus
    - INGRESS_NAME=my-ingress
    - KASTEN_RELEASE=my-kasten

    # Install Fluent Bit from Helm Repo
    - |
      if ! helm list -n default --all --short | grep -q "^$FLUENT_BIT_RELEASE$"; then
       echo "Installing Helm chart $FLUENT_BIT_RELEASE..."
       helm install $FLUENT_BIT_RELEASE fluent/fluent-bit --namespace default
      else
        echo "Helm chart $FLUENT_BIT_RELEASE is already installed"
      fi

    # Install Redis using Helm
    - |
      if ! helm list -n default --all --short | grep -q "^$REDIS_RELEASE$"; then
        echo "Installing Helm chart $REDIS_RELEASE..."
        helm install $REDIS_RELEASE bitnami/redis --namespace default
      else
        echo "Helm chart $REDIS_RELEASE is already installed"
      fi

    # Install Nginx server using Helm
    - |
      if ! helm list -n default --all --short | grep -q "^$NGINX_RELEASE$"; then
        echo "Installing Helm chart $NGINX_RELEASE..."
        helm install $NGINX_RELEASE bitnami/nginx --namespace default
      else
        echo "Helm chart $NGINX_RELEASE is already installed"
      fi

    # Install PostgreSQL using Helm
    - |
      if ! helm list -n default --all --short | grep -q "^$POSTGRES_RELEASE$"; then
       echo "Installing Helm chart $POSTGRES_RELEASE..."
       helm install $POSTGRES_RELEASE bitnami/postgresql --namespace default
      else
        echo "Helm chart $POSTGRES_RELEASE is already installed"
      fi

    # Install Prometheus using Helm
    - |
      if ! helm list -n default --all --short | grep -q "^$PROMETHEUS_RELEASE$"; then
       echo "Installing Helm chart $PROMETHEUS_RELEASE..."
       helm install $PROMETHEUS_RELEASE prometheus-community/prometheus --namespace default
      else
       echo "Helm chart $PROMETHEUS_RELEASE i s already installed"
      fi

    # Install nginx-ingress using Helm
    - |
      if ! helm list -n default --all --short | grep -q "^$INGRESS_NAME$"; then
        echo "Installing Helm chart $RELEASE_NAME..."
        helm install $INGRESS_NAME ingress-nginx/ingress-nginx --namespace default
      else
        echo "Helm chart $INGRESS_NAME is already installed"
      fi

    # Install Kasten K10 using Helm
    - |  
      if ! helm list -n default --all --short | grep -q "^$KASTEN_RELEASE$"; then
        echo "Installing Helm chart $KASTEN_RELEASE..."
        helm install $KASTEN_RELEASE kasten/k10 --namespace default
      else
       echo "Helm chart $KASTEN_RELEASE is already installed"
      fi

    # Create the argocd namespace if it doesn't exist
    - |
      if ! kubectl get namespace argocd &> /dev/null; then
        echo "Creating namespace argocd..."
        kubectl create namespace argocd
      else
        echo "Namespace argocd already exists."
      fi

    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - kubectl apply -f ../application.yaml
   
  needs:
    - job: apply
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve
  dependencies:
    - plan
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'