---
- name: Update pkg & install Openssl Helm on localhost
  hosts: terraform-host
  become: yes
  tasks:
    # Basic tasks to install helm 
    - name: Update package repositories
      community.general.apk:
        update_cache: yes

    - name: Install OpenSSL (Secure Sockets Layer - required for Helm installation)
      community.general.apk:
        name: openssl
        state: latest

    - name: Download and Install Helm
      shell: "curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | sh"
      register: helm_install_result
      changed_when: helm_install_result.stdout_lines
    
    - name: Display Helm installation status
      debug:
        msg: "Helm {{ 'installed' if helm_install_result.stdout_lines else 'already installed' }}"
    
    # Helm repo tasks

    - name: Add Redis/SQL/nginx-server Database Helm Repository
      ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Add Helm repository nginx-ingress controller
      ansible.builtin.command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Add Kasten Helm Repository
      ansible.builtin.command: helm repo add kasten https://charts.kasten.io/

    - name: Add Fluent Bit Helm Repository
      ansible.builtin.command: helm repo add fluent https://fluent.github.io/helm-charts

    - name: Add Prometheus Helm Repository
      ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Search Helm Charts
      ansible.builtin.command: helm search repo

    - name: Update Helm Repositories
      ansible.builtin.command: helm repo update

    # Helm install tasks