---
controller:
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"
  ingressClassResource:
    name: external-nginx
    enabled: true
    default: false
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ingress-nginx
        topologyKey: "kubernetes.io/hostname"
  replicaCount: 1
  admissionWebhooks:
    enabled: false
  service:
    annotations:
      cloud.google.com/load-balancer-type: External
  metrics:
    enabled: false

# WORK IN PROGRESS

#postgres:
#  replicaCount: 1
#  image:
#    repository: postgres
#    tag: 13
#  databaseName: mydb
#  username: myuser
#  resources:
#    requests:
#      memory: "256Mi"
#     cpu: "100m"
#   limits:
#      memory: "512Mi"
#      cpu: "200m"
#  service:
#    type: ClusterIP

#dns:
#  server: 8.8.8.8
#  search: example.com

#prometheus:
#  replicaCount: 1
#  image:
#    repository: prom/prometheus
#    tag: v2.30.1
#  resources:
#    requests:
#      memory: "256Mi"
#      cpu: "100m"
#    limits:
#      memory: "512Mi"
#      cpu: "200m"
#  service:
#    type: ClusterIP